name: CheckAllBuildConfigurations
on:   
  workflow_dispatch:

jobs:  
  
  build:    
    strategy:
      matrix:
        buildConfiguration: [Debug, Release]
        dotNetVersion: [6.0.x, 8.0.x]
  
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotNetVersion }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c ${{ matrix.buildConfiguration }} --no-restore    
  
