name: DeployToAzure
on:
  workflow_call: 
    inputs:
      deployedArtifactName:
        description: "The name of the Deployed asp.net Core Web Application to be deployed to Azure"
        required: true
        type: string
        default: "published-app-data"       
    secrets:
      azureLogin:
        required: true
      azurePassword:
        required: true
    outputs:
       azureDeploymentResult:
        description: "Result of an Azure Deployment process"
        value: ${{ jobs.deployToAzure.outputs.deploymentResult }}      
jobs:  

  deployToAzure:        
    runs-on: ubuntu-latest
    outputs:
      deploymentResult: ${{ steps.azureDeploymentStep.outputs.deploymentResult }}
    steps:
      - name: Download Artifacts        
        uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.deployedArtifactName }}        
      - run: ls      
      - name: Run Deployment To Azure
        id: azureDeploymentStep        
        run: |
          echo "Deploying To Azure"
          echo "Successfullt Deployed To Azure"
          echo "deploymentResult=Successfully Deployed To Azure Using Reusable Workflow" >> $GITHUB_OUTPUT

  
