name: Main CI
on: 
  push:
    branches:
      - main
  workflow_dispatch:    

env:
  Environment: "Prod"

jobs:
  build:
    environment: env:Environment
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c ${{vars.BUILDCONFIGURATION}} --no-restore
      - name: Test
        run: dotnet test --no-restore --no-build
  publish:
    environment: Prod
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Publish
        run: dotnet publish WebApplication/WebApplication.csproj -c ${{vars.BUILDCONFIGURATION}} -r ${{vars.BUILDPLATFORM}} -o bin/published/
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: published-app
          path: bin/published/
  deploy:
    environment: Prod
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v7
        with:
          name: published-app
      - run: ls
      - run: echo "Deployed to ${{ env.Environment }}"
      - run: echo "Sql Server Login ${{ secrets.SQLSERVER_LOGIN }}"
      - run: echo "Sql Server PASSWORD ${{ secrets.SQLSERVER_PASSWORD }}"
  
